LedgerHQ/ledger-asset-dapps

- ethereum/1inch/abis/0x1111111254fb6c44bac0bed2854e76f90643097d.abi.json
- ethereum/1inch/b2c.json
- ethereum/1inch/b2c_signatures.json
To add a new contract [1inchV4](https://etherscan.io/address/0x1111111254fb6c44bac0bed2854e76f90643097d)
For now only one method "swap" is allowed that is identical to swap from 1inchV3.
No changes in plugin itself required.
Signature needs to be added.
[Transaction example is here](https://etherscan.io/tx/0x4c4c4fc1e7d74b4cb9f193630b5324413a1a010868dc7a2078287d5a02875fc6)
> added new 1inchV4 contract method swap

- ethereum/compound/b2c.json
This patch removes errant `erc20OfInterest` segments added to cCOMP incorrectly. They had `path.1` which is not a data argument of these functions and is causing failures from Ledger users who are interacting with cCOMP.  This is high priority as it's actively blocking usage of Ledger for any interactions of cCOMP.
> Remove Errant erc20OfInterest Segments

- ethereum/lido/parsers.json
- The __eth__ for a transaction amount is useful to understand where it comes from but it add a lot of complexity for Firmware team
> remove __eth__ from lido's parser

- ethereum/paraswap/parsers.json
- ethereum/uniswap/parsers.json
- When eth is considered in the transaction (i.e. a swap) the value is not only in the transaction but also in the payload
- We can only consider the one in the payload
> Remove transaction when amount in payload

- ethereum/paraswap/parsers.json
- Paraswap has some edge cases when interacting with ethereum. Eth is represented as a token with 0xeeeeeee as an address. Parsers need to hold this information to ease the work of FW team.
https://ledgerhq.atlassian.net/wiki/spaces/TA/pages/3600023571/ARCH+SCI+Handling+Paraswap+special+cases
> add ethContractAddress to methods

- ethereum/lido/parsers.json
We are addind a default token value for the submit method of lido. Hence we need and option to spot it.
> Add option ethContractAddress to lido

- ethereum/nft/parsers.json
The arguments data is in bytes; not yet supported. 
Development time would be too long for an arguments that product don't estimate that much important.
> [VG-9445] Remove temporarly data from safeTransferFrom

- scripts/validate_files.py
- scripts/validation/validators.py
Add the following validators to quickly invalidate parser files:
- presence of parser validation schema
- unicity of parser IDs on a given blockchain
- contract addresses correctly formatted with EIP55
- function mapping between parser and ABI
- arguments mapping between a function and its screen
> feature: Add validators on parser files

- ethereum_goerli/[ L ] Market/b2c.json
MultiMintSign (erc721) && Inspiredy By Ledger (1155) contract were with the same contract address. 
This is a fix for the 721 with the correct address 0x16fe8822d358a3f6ad52dd060cdec409e4b6d409
> Fix duplicate contracts

- ethereum/opensea/parsers.json
This function results in `hsm.exceptions.HsmError: (912, 'Transfer of ERC20 tokens from a parent Eth account is forbidden', '', '')` when running vault-python-tests.
> Remove '0xa9059cbb' transfer function from opensea DApp

- arbitrum/uniswap/abis/0x3fc91a3afd70395cd496c647d5a6cc9d4b2b7fad.abi.json
- arbitrum/uniswap/b2c.json
- avalanche/uniswap/abis/0x3fc91a3afd70395cd496c647d5a6cc9d4b2b7fad.abi.json
- avalanche/uniswap/b2c.json
- base/uniswap/abis/0x3fc91a3afd70395cd496c647d5a6cc9d4b2b7fad.abi.json
- base/uniswap/b2c.json
- blast/b2c.schema.json
- blast/uniswap/abis/0x3fc91a3afd70395cd496c647d5a6cc9d4b2b7fad.abi.json
- blast/uniswap/b2c.json
- bsc/uniswap/abis/0x3fc91a3afd70395cd496c647d5a6cc9d4b2b7fad.abi.json
- bsc/uniswap/b2c.json
- celo/uniswap/abis/0x3fc91a3afd70395cd496c647d5a6cc9d4b2b7fad.abi.json
- celo/uniswap/b2c.json
- ethereum/uniswap/abis/0x3fc91a3afd70395cd496c647d5a6cc9d4b2b7fad.abi.json
- ethereum/uniswap/b2c.json
- optimism/uniswap/abis/0x3fc91a3afd70395cd496c647d5a6cc9d4b2b7fad.abi.json
- optimism/uniswap/b2c.json
- polygon/uniswap/abis/0x3fc91a3afd70395cd496c647d5a6cc9d4b2b7fad.abi.json
- polygon/uniswap/b2c.json
In order to support the new [Uniswap external plugin](https://github.com/LedgerHQ/app-plugin-uniswap) we need the signature capable of launching the external plugin `Uniswap` with the selector of its `execute` method (https://etherscan.io/address/0x3fc91a3afd70395cd496c647d5a6cc9d4b2b7fad#writeContract#F3).
No other information is required (like `erc20OfInterest` or ABIs) as the tokens involved are not retrievable via ABI decoding, but require manual parsing, which will be done in `@ledgerhq/hw-app-eth`.
> Add Uniswap `b2c.json` files for nano app external plugin

- arbitrum/eip712.schema.json
- arbitrum_sepolia/eip712.schema.json
- avalanche/eip712.schema.json
- base/eip712.schema.json
- base_sepolia/eip712.schema.json
- blast/eip712.schema.json
- bsc/eip712.schema.json
- celo/eip712.schema.json
- ethereum/eip712.schema.json
- ethereum/smartcredit/eip712.json
- ethereum_sepolia/eip712.schema.json
- fantom/eip712.schema.json
- optimism/eip712.schema.json
- optimism_sepolia/eip712.schema.json
- polygon/eip712.schema.json
- polygon_mumbai/eip712.schema.json
- polygon_zk_evm/eip712.schema.json
- scroll/eip712.schema.json
- forbid empty labels, or longer than 39 characters (ethereum app limit)
- forbid empty mappings / empty messages or contracts lists
- fix SmartCredit.io descriptor breaking rule (just show all fields)
> EIP-712: implement stricter validations

- arbitrum/uniswap/eip712.json
- arbitrum_sepolia/uniswap/eip712.json
- avalanche/uniswap/eip712.json
- base/uniswap/eip712.json
- base_sepolia/uniswap/eip712.json
- blast/uniswap/eip712.json
- bsc/uniswap/eip712.json
- celo/uniswap/eip712.json
- ethereum/uniswap/eip712.json
- ethereum_sepolia/uniswap/eip712.json
- optimism/uniswap/eip712.json
- optimism_sepolia/uniswap/eip712.json
- polygon/uniswap/eip712.json
- polygon_mumbai/uniswap/eip712.json
Array elements cannot be referenced individually yet. Fallback to what is supported for now
> EIP-712: fix Uniswap EIP-712 descriptors using unsupported syntax

- arbitrum/permit/eip712.json
- avalanche/permit/eip712.json
- bsc/permit/eip712.json
- ethereum/permit/eip712.json
- fantom/permit/eip712.json
- optimism/permit/eip712.json
- polygon/permit/eip712.json
Will default to `verifyingContract` as the token ref.
See:
- https://ledgerhq.atlassian.net/browse/BACK-7352
- https://github.com/LedgerHQ/crypto-assets/pull/1194
- https://github.com/LedgerHQ/python-eip712/pull/8
> BACK-7352: Permit EIP-712: switch allowance to `format=amount`

- .github/workflows/ci.yml
CI fails at PR comment for external contriibutors: https://github.com/LedgerHQ/ledger-asset-dapps/actions/runs/9989369000/job/27673680234?pr=202#step:7:143
> ci: add missing permissions

- scripts/validate_files.py
- scripts/validation/validators.py
Only allow one plugin for a given (chain_id, contract, selector) triplet
i.e. what we want to forbid is
```
(ethereum, 0xa356867fdcea8e71aeaf87805808803806231fdc, 0x1e6d24c2, DODO)
(ethereum, 0xa356867fdcea8e71aeaf87805808803806231fdc, 0x1e6d24c2, Harvest)
```
In that case a message like this, is printed:
```
Validation error: File ./ethereum/opensea/b2c.json and file ./ethereum/dodo/b2c.json 
bind (blockchain=ethereum, contract=0xa356867fdcea8e71aeaf87805808803806231fdc, 
selector=0x1e6d24c2) to different plugins DODO and Harvest respectively, 
please remove one of the bindings
```
> BACK-7439: only allow one plugin for a given (chain_id, contract, selector) triplet

- ethereum/nft/parsers.json
The logic in the HSM code differs between Blue and Stax.
- Blue: NFT function screens are described in parsers.json and the final screen flow is a concatenation of those function screens with the sci clear sign screens defined in the crypto-assets repo
- Stax: NFT clearsign screens are fully described under `ethereum/nft/parsers.json`. There is not concatenation
> feat(VG-15990): add stax nft clearsign screens

- .github/workflows/main.yml
LedgerHQ/python-erc7730 also uses LedgerHQ/ledger-asset-dapps for integration tests.
> ci: trigger update on LedgerHQ/python-erc7730 on merge to main

- ethereum_goerli/nft/parsers.json
- ethereum_sepolia/nft/parsers.json
To ease review, the result of the following command shows the diff between ethereum mainnet NFT screens definition and testnet screens definition
```
diff assets/dapps/ethereum_sepolia/nft/parsers.json assets/dapps/ethereum/nft/parsers.json
<     "blockchainName": "ethereum_sepolia",
<     "chainId": 11155111,
---
>     "blockchainName": "ethereum",
>     "chainId": 1,
```
```
diff assets/dapps/ethereum_goerli/nft/parsers.json assets/dapps/ethereum/nft/parsers.json
<     "blockchainName": "ethereum_goerli",
<     "chainId": 5,
---
>     "blockchainName": "ethereum",
>     "chainId": 1,
```
> feat(stax): add NFT screens definition for ethereum testnets

- .github/workflows/main.yml
`LedgerHQ/crypto-assets-clear-signing-initiative` is now merged and archived
> ci: remove trigger on archived repository

- bsc/stakekit/abis/0x0000000000000000000000000000000000002002.abi.json
- bsc/stakekit/b2c.json
Added support for the StakeHub smart contract on BSC network.
Methods supported:
- undelegate
- redelegate
- delegate
- claim
> feat: added support for StakeKit smart contract on BSC
