LedgerHQ/ledger-asset-dapps

.github/CODEOWNERS, .github/workflows/ci.yml, Pipfile, Pipfile.lock, ethereum/1inch/abis/0x11111112542D85B3EF69AE05771c2dCCff4fAa26.json, ethereum/1inch/b2c.json, ethereum/aave/b2c.json, ethereum/compound/b2c.json, ethereum/lido/abis/0x7f39c581f595b53c5cb19bd0b3f8da6c935e2ca0.json, ethereum/lido/abis/0xae7ab96520de3a18e5e111b5eaab095312d7fe84.json, ethereum/lido/b2c.json, ethereum/paraswap/b2c.json, ethereum/schema.json, scripts/validate_files.py, scripts/validation/validators.py
- Fix formatting of the json data files to use the standard:
- 4 spaces indentation
- sorted keys
- Added a basic CI check for format + json schema validation
- Added CODEOWNERS file to better control PR approvals
=> Fix formatting of json data files

ethereum/lido/parsers.json, ethereum/paraswap/parsers.json, ethereum/parsers.schema.json, ethereum/uniswap/parsers.json, ethereum_ropsten/parsers.schema.json
=> Add lido paraswap uniswap

bsc/b2c.schema.json, ethereum/parsers.schema.json, ethereum_ropsten/parsers.schema.json, scripts/validation/validators.py
Those screens will be used to override the default screens generated by the CAL
=> VG 4526 - Update parsers schema to allows screens

ethereum/lido/parsers.json, ethereum/paraswap/parsers.json, ethereum/parsers.schema.json, ethereum/uniswap/parsers.json
- Addresses used to be lowercased
- It now needs to be EIP55
=> [VG-5453] Revert lowercasing

ethereum/paraswap/parsers.json
- After discussion; https://docs.google.com/document/d/1bfX2wJ9L625yZeHtnmJwPC2BQI1SVLvGiofhaBTtI_M/edit#
- We decided to only parse the last involved pool
- Linked with https://github.com/LedgerHQ/python-smart-contract/pull/39
=> Parse only pools paraswap v5

ethereum/lido/parsers.json, ethereum/paraswap/parsers.json, ethereum/parsers.schema.json, ethereum/uniswap/parsers.json, ethereum_goerli/parsers.schema.json, ethereum_ropsten/b2c.schema.json, ethereum_ropsten/parsers.schema.json, scripts/validate_files.py, scripts/validation/validators.py
=> Matching new PSM version

ethereum/lido/parsers.json, ethereum/paraswap/parsers.json, ethereum/parsers.schema.json
* New screen versions for SCI.
* Use static entries for some function names
* Change one function type value
=> Screen last version

ethereum/nft/parsers.json
Update Screens for NFTs to match https://www.figma.com/file/BK1aCdRYEoRrfcmgtH5Xd1/Smart-Contract-Interactions-%26-dApp-Browser?node-id=646%3A7231 
Adding method safeTransferFrom with data for ERC721
=> Update screen and functions for NFT

ethereum/nft/abis/0x1155000000000000000000000000000000000000.abi.json, ethereum/nft/abis/0x7210000000000000000000000000000000000000.abi.json, ethereum/nft/parsers.json, ethereum/parsers.schema.json
This reverts commit dd6926fff1e86b61b48473e4882cbc308681a653.
Adding back NFT ClearSign generic parsers
=> Revert "[VG-9445] Revert NFT generic parsers"

ethereum/opensea/eip712.json, scripts/validation/validators.py
https://ledgerhq.atlassian.net/browse/BACK-4166
=> BACK-4166: Fix EIP712 schema validator reordering too much, fix Opensea schema order

ethereum/aave/parsers.json
Fix the repayETH label, and rework order of params for borrowETH.
=> Fix screens for Aave - Update parsers.json

polygon/paraswap/parsers.json
Param label is Amout instead of Amount
=> Fix typo for swapOnUniswapFork

bsc/paraswap/parsers.json, bsc/parsers.schema.json
This reverts commit f6066d3396dc7793739cb7fff9c8e262507b23f3, reversing changes made to bb4e93b1553920ee473a4577c1cb06ce96bb2965.
=> Add back bep20 (revert the revert of the merge)

ethereum/figment/abis/0xf0075b3cf8953d3e23b0ef65960913fd97eb5227.abi.json, ethereum/figment/b2c.json, ethereum_goerli/figment/abis/0x94a2da805867c962148d3832d9afc512034a62c5.abi.json, ethereum_goerli/figment/b2c.json
Adding the Figment Goerli and Mainnet ABIs and selectors for the deposit contract.
=> feat: add Figment Goerli and Mainnet contracts

polygon/lens/eip712.json
=> fields fixing 16

avalanche/eip712.schema.json
This provides the metadata for valid EIP-712 structured data within the avalanche chain.
=> feature(avalanche): Add schema to support eip712

ethereum_holesky/b2c.schema.json, ethereum_holesky/figment/abis/0xa627f94a8f94e4713d38f52ac3a6377b0a111d47.abi.json, ethereum_holesky/figment/b2c.json, ethereum_holesky/parsers.schema.json
Adding support for Holesky and including Figment's Holesky ABI for the deposit contract
=> feat: add holesky and figment contract

ethereum/ens/abis/0x253553366da8546fc250f225fe3d25d0c782303b.abi.json, ethereum/ens/abis/0x9062c0a6dbd6108336bcbe4593a3d1ce05512069.abi.json, ethereum/ens/abis/0xa12159e5131b1eef6b4857eee3e1954744b5033a.abi.json, ethereum/ens/abis/0xa58e81fe9b61b5c3fe2afd33cf304c454abfc7cb.abi.json, ethereum/ens/b2c.json, ethereum/swell/abis/0xf951e335afb289353dc249e82926178eac7ded78.abi.json, ethereum/swell/b2c.json
- Add stake contract to swell
- update abis for ENS
=> Update Swell and Ens

ethereum/stader/abis/0x036676389e48133b63a802f8635ad39e752d375d.abi.json, ethereum/stader/b2c.json
- added abi for Kelp Deposit Pool
- updated selectors for ethx deposit and request_withdraw
=> Update stader kelp abis

arbitrum/permit/eip712.json, avalanche/permit/eip712.json, bsc/permit/eip712.json, ethereum/permit/eip712.json, fantom/eip712.schema.json, fantom/permit/eip712.json, optimism/permit/eip712.json, polygon/permit/eip712.json
added these contracts for these networks: (from https://belactriple9.github.io/1inchSupportedPermits/)
all tokens are present in CAL.
ethereum
---------
USDC https://etherscan.io/address/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48
DAI https://etherscan.io/address/0x6B175474E89094C44Da98b954EedeAC495271d0F
AAVE https://etherscan.io/address/0x7Fc66500c84A76Ad7e9c93437bFc5Ac33E2DDaE9
bsc
----
https://bscscan.com/address/0x111111111117dC0aa78b770fA6A738034120C302 
https://bscscan.com/address/0x7e624fa0e1c4abfd309cc15719b7e2580887f570
Polygon
-------
https://polygonscan.com/token/0x27F8D03b3a2196956ED754baDc28D73be8830A6e
amWETH https://polygonscan.com/token/0x28424507fefb6f7f8e9d3860f56504e4e5f5f390
avalanche_c_chain
------------------ …
=> BACK-7314: Add Permit EIP-712 descriptors

arbitrum/uniswap/eip712.json, arbitrum_sepolia/uniswap/eip712.json, base/uniswap/eip712.json, base_sepolia/uniswap/eip712.json, blast/uniswap/eip712.json, bsc/uniswap/eip712.json, celo/uniswap/eip712.json, ethereum/uniswap/eip712.json, ethereum_sepolia/uniswap/eip712.json, optimism/uniswap/eip712.json, optimism_sepolia/uniswap/eip712.json, polygon/uniswap/eip712.json, polygon_mumbai/uniswap/eip712.json
from @lcastillo-ledger :)
supersedes #186
=> BACK-7120: Add uniswapX EIP712 definitions

arbitrum/1inch/eip712.json, arbitrum/uniswap/eip712.json, arbitrum_sepolia/uniswap/eip712.json, avalanche/uniswap/eip712.json, base/uniswap/eip712.json, base_sepolia/uniswap/eip712.json, blast/uniswap/eip712.json, bsc/1inch/eip712.json, bsc/uniswap/eip712.json, celo/uniswap/eip712.json, ethereum/1inch/eip712.json, ethereum/uniswap/eip712.json, ethereum_sepolia/uniswap/eip712.json, optimism/1inch/eip712.json, optimism/uniswap/eip712.json, optimism_sepolia/uniswap/eip712.json, polygon/1inch/eip712.json, polygon/uniswap/eip712.json, polygon_mumbai/uniswap/eip712.json
See https://ledgerhq.atlassian.net/browse/BACK-7356
=> BACK-7356: EIP-712 descriptors: add missing "format": "token" fields

.github/workflows/ci.yml, scripts/validate_files.py, scripts/validation/validators.py
- reduce verbosity
- attach a comment with validation report
=> ci: validation report improvements

arbitrum/1inch/eip712.json, arbitrum/permit/eip712.json, arbitrum/uniswap/eip712.json, arbitrum_sepolia/uniswap/eip712.json, avalanche/permit/eip712.json, avalanche/uniswap/eip712.json, base/uniswap/eip712.json, base_sepolia/uniswap/eip712.json, blast/uniswap/eip712.json, bsc/1inch/eip712.json, bsc/permit/eip712.json, bsc/uniswap/eip712.json, celo/uniswap/eip712.json, ethereum/1inch/eip712.json, ethereum/permit/eip712.json, ethereum/uniswap/eip712.json, ethereum_sepolia/uniswap/eip712.json, fantom/permit/eip712.json, optimism/1inch/eip712.json, optimism/permit/eip712.json, optimism/uniswap/eip712.json, optimism_sepolia/uniswap/eip712.json, polygon/1inch/eip712.json, polygon/permit/eip712.json, polygon/uniswap/eip712.json, polygon_mumbai/uniswap/eip712.json
- renaming EIP 712 labels for permit
- renaming EIP 712 labels for Uniswap
- renaming EIP 712 labels for 1inch
=> Feat/back 7381/labels

.github/workflows/ci.yml
=> ci: use org token

.github/workflows/ci.yml
tried #204, #205, #206, can't get it to work :shrug:
=> ci: remove comment steps, does not work with external contributions

ethereum_holesky/coinbase/abis/0xa55416de5de61a0ac1aa8970a280e04388b1de4b.abi.json, ethereum_holesky/coinbase/b2c.json, ethereum_holesky/coinbase/staking.json
Adds first pass at Coinbase Staking holesky testnet contract abi's.
=> Adds Contracts for Coinbase Staking

.github/workflows/pull_request.yml
=> ci: remove labels management

ethereum/coinbase/abis/0xc4dcb059dd98b45b090da8982234c61d0b9e84f9.abi.json, ethereum/coinbase/b2c.json
Adds Coinbase Staking mainnet contract abi's.
=> Adds Coinbase mainnet contracts

ethereum/chorus/abis/0xe6d8d8ac54461b1c5ed15740eee322043f696c08.abi.json, ethereum/chorus/b2c.json
Functionality for Chorus One Stakewise contracts.
Plugin hosted at https://github.com/ChorusOne/ledger-live-plugin
=> Add ChorusOne plugin files

ethereum_holesky/bricktowers/b2c.json, ethereum_holesky/coinbase/b2c.json, ethereum_holesky/figment/b2c.json, ethereum_holesky/kiln/b2c.json, ethereum_holesky/p2p/b2c.json, ethereum_ropsten/rarible/b2c.json, polygon/rarible/b2c.json, polygon/stakedao/b2c.json
Files changed 
./polygon/stakedao/b2c.json 
./polygon/rarible/b2c.json
./ethereum_ropsten/rarible/b2c.json
./ethereum_holesky/figment/b2c.json
./ethereum_holesky/coinbase/b2c.json
./ethereum_holesky/p2p/b2c.json
./ethereum_holesky/bricktowers/b2c.json
./ethereum_holesky/kiln/b2c.json
=> chore(BACK-8785): Add erc20OfInterest empty array to contracts for testnets
